<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-H6V9FIN" failures="1" tests="2" name="Surefire test" time="35.471" errors="0" timestamp="2022-04-24T22:41:21 BRT">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.161"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="22.451">
    <failure type="java.lang.AssertionError" message="expected [] but found [Your data has been successfully deleted from the database.]">
      <![CDATA[java.lang.AssertionError: expected [] but found [Your data has been successfully deleted from the database.]
at provaSicrediWeb@1.0-SNAPSHOT/paginas.Metodos.validarTexto(Metodos.java:276)
at provaSicrediWeb@1.0-SNAPSHOT/steps.Steps.valido_a_exclusao(Steps.java:111)
at âœ½.valido a exclusao(file:///C:/Users/erick/IdeaProjects/provaSicrediWeb/src/test/resources/features/provaSicredi.feature:30)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Surefire test -->
